# Generated by Django 5.0.6 on 2024-05-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment_address',
        ),
    ]
